[package]

name = "nn"
version = "0.0.1"
authors = ["Jack Montgomery <jackm321@gmail.com>"]
repository = "https://github.com/jackm321/rust_nn"

description = """
A multilayer feedforward backpropagation neural network library
"""

keywords = ["nn", "ann", "neural", "backpropagation", "neural network",
            "artificial neural network"]

[dependencies]
rand = "0.2.0"